services:
  db:
    image: mysql
    container_name: mysql-crud-jdbc
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ramon_data:/var/lib/mysql
volumes:
  ramon_data: